from copy_template import CopyTemplate

conn_string = "postgresql://postgres:postgres@postgres:5432/imdb"

known_types = {
    "alternative",
    "dvd",
    "festival",
    "imdbDisplay",
    "original",
    "tv",
    "video",
    "working"
}

known_attributes = {
    "16mm release title",
    "16mm rental title",
    "3-D version",
    "3-D video title",
    "8mm release title",
    "added framing sequences and narration in Yiddish",
    "alternative spelling",
    "alternative transliteration",
    "American Mutoscope & Biograph catalog title",
    "anthology series",
    "approximation of original mirrored title",
    "armed forces circuit title",
    "attributes",
    "Bable dialect title",
    "Berlin film festival title",
    "Bilbao festival title",
    "bootleg title",
    "bowdlerized title",
    "cable TV title",
    "Cannes festival title",
    "censored version",
    "closing credits title",
    "complete title",
    "copyright title",
    "correct transliteration",
    "cut version",
    "daytime version title",
    "director's cut",
    "dubbed version",
    "DVD box title",
    "DVD menu title",
    "eighteenth season title",
    "eighth season title",
    "eleventh season title",
    "English translation of working title",
    "english transliteration",
    "expansion title",
    "fake working title",
    "fifteenth season title",
    "fifth part title",
    "fifth season title",
    "first episodes title",
    "first episode title",
    "first part title",
    "first season title",
    "first segment title",
    "fortieth season title",
    "fourteenth season title",
    "fourth part title",
    "fourth season title",
    "game box title",
    "GameCube version",
    "Hakka dialect title",
    "IMAX version",
    "incorrect title",
    "informal alternative title",
    "informal English title",
    "informal literal English title",
    "informal literal title",
    "informal short title",
    "informal title",
    "last season title",
    "late Sunday edition",
    "LD title",
    "literal English title",
    "literal French title",
    "literal title",
    "literal translation of working title",
    "Locarno film festival title",
    "longer version",
    "long new title",
    "long title",
    "Los Angeles premiere title",
    "Los Angeles première title",
    "MIFED title",
    "modern translation",
    "new syndication title",
    "new title",
    "nineteenth season title",
    "ninth season title",
    "non-modified Hepburn romanization",
    "original pilot title",
    "original script title",
    "original subtitled version",
    "orthographically correct title",
    "Pay-TV title",
    "PC version",
    "POLart",
    "poster title",
    "premiere title",
    "première title",
    "pre-release title",
    "promotional abbreviation",
    "promotional title",
    "racier version",
    "recut version",
    "redubbed comic version",
    "reissue title",
    "rerun title",
    "restored version",
    "review title",
    "R-rated version",
    "rumored",
    "second copyright title",
    "second part title",
    "second season title",
    "second segment title",
    "segment title",
    "series title",
    "seventeenth season title",
    "seventh season title",
    "short title",
    "short version",
    "silent version",
    "sixteenth season title",
    "sixth season title",
    "soft porn version",
    "subtitle",
    "summer title",
    "syndication title",
    "teaser title",
    "tenth season title",
    "theatrical title",
    "third and fourth season title",
    "third part title",
    "third season title",
    "third segment title",
    "thirteenth season title",
    "thirtieth season title",
    "thirtyeighth season title",
    "thirtyfifth season title",
    "thirtyfirst season title",
    "thirtyfourth season title",
    "thirtyninth season title",
    "thirtysecond season title",
    "thirtyseventh season title",
    "thirtysixth season title",
    "thirtythird season title",
    "title for episodes with guest hosts",
    "trailer title",
    "transliterated title",
    "TV listings title",
    "twelfth season title",
    "twentieth season title",
    "twentyeighth season title",
    "twentyfifth season title",
    "twentyfirst season title",
    "twentyfourth season title",
    "twentyninth season title",
    "twentysecond season title",
    "twentyseventh season title",
    "twentysixth season title",
    "twentythird season title",
    "unauthorized video title",
    "uncensored intended title",
    "Venice film festival title",
    "video box title",
    "video box title ",
    "video catalogue title",
    "video CD title",
    "videogame episode",
    "weekend title",
    "X-rated version",
    "Yiddish dubbed",
    "YIVO translation"
}

copy_templates = [
    TitleBasicsTemplate(
        "title.akas.tsv.gz", {
            "language": [
                "languageId",
                "languageName"
            ],
            "region": [
                "regionId",
                "regionName"
            ],
            "titleAkas": [
                "akasId",
                "titleId",
                "ordering",
                "title",
                "regionId",
                "languageId",
                "isOriginalTitle"
            ],
            "akaType": [
                "akaTypeId",
                "akaTypeName"
            ],
            "akaType_titleAkas": [
                "akaTypeId",
                "titleId"
            ],
            "attribute": [
                "attributeId",
                "attributeText"
            ],
            "attribute_titleAkas": [
                "attributeId",
                "akasId"
            ]
         }
]
